### ISSUE TITLE
项目是否支持 weex platform add ios 命令？

### ISSUE THREAD

**Issue by ggchxx** [GeoffZhu/weex-template#1]
使用该命令 weex platform add ios
提示
/Users/User/.xtoolkit/node_modules/weexpack/src/platform/tools.js:191
    throw new CordovaError('Current working directory is not a weex project.');
    ^
weexpack error: Current working directory is not a weex project.

**Comment by GeoffZhu** [comment]
可以，本周支持 @ggchxx

**Comment by GeoffZhu** [comment]
你的weexpack是什么版本的？
我这里做了测试
weexpack v1.0.13
可以正常使用

**Comment by ggchxx** [comment]
weex -v
  -v1.2.7
 - weexpack : v1.0.8
 - weex-debugger : v1.0.0
 - weex-builder : v0.3.12
 - weex-previewer : v1.4.4
目前用的这个版本

**Comment by GeoffZhu** [comment]
我这里是支持的，并且我已经把ios生成出的项目直接放在了仓库中

**Comment by GeoffZhu** [comment]
@ggchxx 我今天更新了很多东西，也修复了一些bug，，如果你在使用，有什么吐槽的，尽情的来吧 😊
